type DataType = {
  group: number;
  id: number;
  name: string;
}[][];

export const data: DataType = [
  [
    { group: 1, id: 1, name: "Mrs. Nataline Fernandes" },
    { group: 1, id: 2, name: "Mrs. Meena Sharma" },
    { group: 1, id: 3, name: "Mrs. Vanadana Mahajan" },
    { group: 1, id: 4, name: "Mrs. Asha Harane" },
    { group: 1, id: 5, name: "Mrs. Shaista Shaikh" },
    { group: 1, id: 6, name: "Mrs. Smita Kharche" },
  ],
  [
    { group: 2, id: 1, name: "Mrs. Saroj Patil" },
    { group: 2, id: 2, name: "Mrs. Jayashree Waghmare" },
    { group: 2, id: 3, name: "Mrs. Priyanka Ghodke" },
    { group: 2, id: 4, name: "Mrs. Kavita Umberkar" },
    { group: 2, id: 5, name: "Mrs. Rashmi Dadhich" },
    { group: 2, id: 6, name: "Mrs. Bhagyashri Patil" },
  ],
  [
    { group: 3, id: 1, name: "Mrs. Dharti Patel" },
    { group: 3, id: 2, name: "Mrs. Mugdha Pawar" },
    { group: 3, id: 3, name: "Mrs. Lalitha Amode" },
    { group: 3, id: 4, name: "Mrs. Sharda Jha" },
    { group: 3, id: 5, name: "Mrs. Sonali Chaudhari" },
    { group: 3, id: 6, name: "Mrs. Sunanda Sontakke" },
  ],
  [
    { group: 4, id: 1, name: "Mrs. Deepa Nathani" },
    { group: 4, id: 2, name: "Mrs. Seema Chaudhari" },
    { group: 4, id: 3, name: "Mrs. Elizabeth Francis" },
    { group: 4, id: 4, name: "Mrs. Shamal Saner" },
    { group: 4, id: 5, name: "Ms. Gumani Chawla" },
    { group: 4, id: 6, name: "Mrs. Lovely Anup Mathew" },
  ],
  [
    { group: 5, id: 1, name: "Mrs. Dipti Gehi" },
    { group: 5, id: 2, name: "Mrs. Nikita Chavan" },
    { group: 5, id: 3, name: "Mrs. Monali Dipak Wani" },
    { group: 5, id: 4, name: "Mrs. Minal Chaudhari" },
    { group: 5, id: 5, name: "Mrs. Kirti" },
    { group: 5, id: 6, name: "Mrs. Vrushali Pankaj Vyavahare" },
    { group: 5, id: 7, name: "Mrs. Rupali Anil Marathe" },
  ],
  [
    { group: 6, id: 1, name: "Mr. John Franklin" },
    { group: 6, id: 2, name: "Mr. Vasudeo Sonar" },
    { group: 6, id: 3, name: "Mr. Kishor Patil" },
    { group: 6, id: 4, name: "Mr. Vithal Chaudhari" },
    { group: 6, id: 5, name: "Mr. Arshad Shaikh" },
    { group: 6, id: 6, name: "Mr. Sushil Chaudhari" },
  ],
  [
    { group: 7, id: 1, name: "Mr. Viquar Shaikh" },
    { group: 7, id: 2, name: "Mr. Rajendra Waghulde" },
    { group: 7, id: 3, name: "Mr. Pravin Patil" },
    { group: 7, id: 4, name: "Mr. Anil Devre" },
    { group: 7, id: 5, name: "Mr. Deoraj" },
    { group: 7, id: 6, name: "Mr. Prince Pillay" },
  ],
  [
    { group: 8, id: 1, name: "Mr. Abhijeet Khachane" },
    { group: 8, id: 2, name: "Mr. Bhushan Chavan" },
    { group: 8, id: 3, name: "Mr. Ashish Patil" },
    { group: 8, id: 4, name: "Mr. Pankaj Mager" },
    { group: 8, id: 5, name: "Mr. Chetan Kailas Kasar" },
    { group: 8, id: 6, name: "Mr. Sanjiv Bornare" },
    { group: 8, id: 7, name: "Mr. Raphael Leo" },
  ],
  [
    { group: 9, id: 1, name: "Mrs. Manjusha Sonar" },
    { group: 9, id: 2, name: "Mrs. Manjusha Deore" },
    { group: 9, id: 3, name: "Mrs. Lata Mahajan" },
    { group: 9, id: 4, name: "Mrs. Pragati Patil" },
    { group: 9, id: 5, name: "Mrs. Rupali Chavan" },
    { group: 9, id: 6, name: "Mrs. Ulka Patil" },
  ],
  [
    { group: 10, id: 1, name: "Mrs. Leena Mahajan" },
    { group: 10, id: 2, name: "Mrs. Philomena Das" },
    { group: 10, id: 3, name: "Mrs. Pallavi Patil" },
    { group: 10, id: 4, name: "Mrs. Prachi Mirashi" },
    { group: 10, id: 5, name: "Mrs. Mitali Lakhere" },
    { group: 10, id: 6, name: "Mrs. Surekha Bhalsane" },
  ],
  [
    { group: 11, id: 1, name: "Mrs. Rakshadevi Tayade" },
    { group: 11, id: 2, name: "Mrs. Priya Sitoke" },
    { group: 11, id: 3, name: "Mrs. Maria Makasare" },
    { group: 11, id: 4, name: "Mrs. Bharti Wath" },
    { group: 11, id: 5, name: "Mrs. Pradnya Bhangale" },
    { group: 11, id: 6, name: "Mrs. Priya Jaiswal" },
  ],
  [
    { group: 12, id: 1, name: "Mrs. Jyoti Thakare" },
    { group: 12, id: 2, name: "Mrs. Smita Shinde" },
    { group: 12, id: 3, name: "Mrs. Bharti Nathani" },
    { group: 12, id: 4, name: "Mrs. Rohini Sonawane" },
    { group: 12, id: 5, name: "Mrs. Yogita Bhirud" },
    { group: 12, id: 6, name: "Mrs. Bhavna H. Chorasiya" },
  ],
  [
    { group: 13, id: 1, name: "Ms. Fatima Patric" },
    { group: 13, id: 2, name: "Mrs. Monica Gonsalves" },
    { group: 13, id: 3, name: "Mrs. Nitu Koli" },
    { group: 13, id: 4, name: "Mrs. Shilpa Mistry" },
    { group: 13, id: 5, name: "Mrs. Leena Chavan" },
    { group: 13, id: 6, name: "Mrs. Sarika Birhade" },
  ],
  [
    { group: 14, id: 1, name: "Mrs. Amruta Mahajan" },
    { group: 14, id: 2, name: "Mrs. Pooja Harshal" },
    { group: 14, id: 3, name: "Mrs. Jayshree Patil" },
    { group: 14, id: 4, name: "Mrs. Varsha Patil" },
    { group: 14, id: 5, name: "Mrs. Rubina Deshpande" },
    { group: 14, id: 6, name: "Mrs. Rukaiya A. Nagri" },
  ],
  [
    { group: 15, id: 1, name: "Mrs. Archana Yuvraj Patil" },
    { group: 15, id: 2, name: "Mrs. Khushali V. Ganatra" },
    { group: 15, id: 3, name: "Mrs. Anju Prashant Borse" },
    { group: 15, id: 4, name: "Mrs. Trisha Patel" },
    { group: 15, id: 5, name: "Mrs. Naidu Rajan Sathya" },
    { group: 15, id: 6, name: "Mrs. Asha Premkumar Ahuja" },
  ],
  [
    { group: 16, id: 1, name: "Mrs. Archana Shelar" },
    { group: 16, id: 2, name: "Ms. Nimish Haque" },
    { group: 16, id: 3, name: "Mrs. Jagruti C. Chaudhari" },
    { group: 16, id: 4, name: "Mrs. Sheetal Lalit Ingale" },
    { group: 16, id: 5, name: "Mrs. Nilangi Ingale" },
    { group: 16, id: 6, name: "Mrs. Sevia Michalle" },
  ],
];
